### ISSUE TITLE
Network config script DNS regex sucks

### ISSUE THREAD

**Issue by CyBeRoni** [vyos/emrk#5]
As per the language in the comment above https://github.com/vyos/emrk/blob/master/etc/init.d/rcS#L251, the regexp sucks. A lot. It won't accept valid IP addresses such any address that doesn't start with 1 or 2. Want to enter 8.8.8.8? Nope.

Since it is very easy to fix an incorrect address (simply edit /etc/resolv.conf to correct it) I suggest simply not validating the input beyond checking for characters that aren't numbers or periods:

`"[0-9.]+"`

**Comment by dmbaturin** [comment]
The tragedy of the project E is its people.
I have no idea what I was thinking when I wrote that, it was clearly supposed to be [1-9][0-9]{,2}
In any case I agree there's no need for thorough validation here.

A bigger problem is that I've been out of the EdgeOS world for quite a while, and since my own equipment is all running VyOS now, I don't need it, so I long lost my cross-compilation setup for MIPS and I'd have to re-do it to make a new build. This thing needs a new maintainer, and if anyone wants to maintain it and extend it to support newer hardware such as ER8 and ERX, I'll gladly offer write access.
